language: node_js
node_js:
  - "6"
after_success:
  - bash <(curl -s https://codecov.io/bash)
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- test/**/*.spec.js
  - codecov

